default_language_version:
  python: python3.10

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-added-large-files
      - id: detect-private-key
      - id: debug-statements
        language_version: python3

  # - repo: local
  #   hooks:
  #     - id: pyupgrade
  #       name: pyupgrade
  #       entry: poetry run pyupgrade --py310-plus
  #       types: [python]
  #       language: system

  # - repo: local
  #   hooks:
  #     - id: isort
  #       name: isort
  #       entry: poetry run isort --settings-path pyproject.toml
  #       types: [python]
  #       language: system

  # - repo: local
  #   hooks:
  #     - id: black
  #       name: black
  #       entry: poetry run black --config pyproject.toml
  #       types: [python]
  #       language: system

  # # - repo: local
  # #   hooks:
  # #     - id: flake8
  # #       name: flake8
  # #       entry: poetry run flake8 --config pyproject.toml
  # #       types: [python]
  # #       language: system
  # #       exclude: pyproject.toml

  # # - repo: local
  # #   hooks:
  # #     - id: mypy
  # #       name: mypy
  # #       entry: poetry run mypy --config-file pyproject.toml
  # #       types: [python]
  # #       language: system
  # #       require_serial: true

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: poetry run pytest -c pyproject.toml tests
  #       types: [python]
  #       language: system
  #       pass_filenames: false
