version: "3.9"

services:
  tubecast:
    container_name: "tubecast"
    image: ghcr.io/martokk/tubecast:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/python_fastapi_stack/data:/python_fastapi_stack/data
      - ./app:/app
    ports:
      - "5000:5000"
