version: "3.9"

services:
  tubecast:
    container_name: "tubecast"
    image: ghcr.io/martokk/tubecast:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/tubecast/data:/tubecast/data
      - ./tubecast:/tubecast
    ports:
      - "5000:5000"
