"""updating Criteria model

Revision ID: 2113c442c1bb
Revises: 9cbfc093593b
Create Date: 2023-03-08 22:06:21.030245

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '2113c442c1bb'
down_revision = '9cbfc093593b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('operator', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('unit_of_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.drop_column('unit_of_measure')
        batch_op.drop_column('value')
        batch_op.drop_column('operator')
        batch_op.drop_column('field')

    # ### end Alembic commands ###
