"""added service to source model

Revision ID: 64abcf0bff79
Revises: 7ac4e8485b8b
Create Date: 2023-02-10 08:39:34.605148

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '64abcf0bff79'
down_revision = '7ac4e8485b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'service')
    # ### end Alembic commands ###
