"""added reverse_import_order to source

Revision ID: 79533f595cf1
Revises: a9112935d34c
Create Date: 2023-03-14 18:45:38.854316

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "79533f595cf1"
down_revision = "a9112935d34c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "reverse_import_order",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("reverse_import_order")

    # ### end Alembic commands ###
