"""reverse rows not Nullable

Revision ID: a9112935d34c
Revises: 71ce2629ce53
Create Date: 2023-03-14 17:44:00.213379

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a9112935d34c'
down_revision = '71ce2629ce53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('uploader',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('uploader_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('released_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('released_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('uploader_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('uploader',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
