"""init

Revision ID: e5de887f0ce5
Revises:
Create Date: 2023-01-24 20:38:39.715917

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e5de887f0ce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('ordered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('feed_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('extractor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('handler', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_source_id'), 'source', ['id'], unique=False)
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.create_foreign_key(None, 'source', 'user', ['created_by'], ['id'])
    op.drop_column('source', 'duration')
    op.drop_column('source', 'owner_id')
    op.drop_column('source', 'uploader_id')
    op.drop_column('source', 'uploader')
    op.drop_column('source', 'title')
    op.drop_column('source', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('thumbnail', sa.VARCHAR(), nullable=True))
    op.add_column('source', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.add_column('source', sa.Column('uploader', sa.VARCHAR(), nullable=True))
    op.add_column('source', sa.Column('uploader_id', sa.VARCHAR(), nullable=True))
    op.add_column('source', sa.Column('owner_id', sa.VARCHAR(), nullable=False))
    op.add_column('source', sa.Column('duration', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.create_foreign_key(None, 'source', 'user', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_source_id'), table_name='source')
    op.drop_column('source', 'created_by')
    op.drop_column('source', 'handler')
    op.drop_column('source', 'extractor')
    op.drop_column('source', 'feed_url')
    op.drop_column('source', 'ordered_by')
    op.drop_column('source', 'logo')
    op.drop_column('source', 'author')
    op.drop_column('source', 'name')
    # ### end Alembic commands ###
